# SPDX-License-Identifier: MIT
"""Build and load typed declaration graph artifacts."""

from __future__ import annotations

import json
import math
import pickle
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from .config import GraphConfig
from .ppr import transition_matrix_from_adjacency, transition_matrix_from_edges
from .schema_inspection import iter_records_from_path


ADJACENCY_FILE = "graph_adjacency.npz"
NODES_FILE = "nodes.json"
EDGES_FILE = "edges.json"
STATS_FILE = "edge_stats.json"
DEPENDENCY_FIELDS = ("dependencies", "deps", "typeReferences", "valueReferences", "references")
_ALWAYS_STRUCTURED_FIELDS = ("dependencies", "deps", "references")
_LEAN_NAME_RE = re.compile(r"(?<![\w.'])[\w][\w']*(?:\.[\w][\w']*)*", re.UNICODE)


class GraphArtifactError(RuntimeError):
    """Raised when graph artifacts are missing or malformed."""


@dataclass
class GraphArtifact:
    adjacency: list[dict[int, float]]
    node_names: list[str]
    node_records: list[dict[str, Any]]
    name_to_node: dict[str, int]
    edge_stats: dict[str, Any]
    edge_types: dict[tuple[int, int], list[str]]
    in_degree: list[int]
    out_degree: list[int]
    transition: Any | None = None
    dangling: np.ndarray | None = None

    def evidence_for(self, source: int, target: int) -> dict[str, Any] | None:
        edge_types = self.edge_types.get((source, target))
        if not edge_types:
            return None
        return {
            "source": self.node_names[source],
            "target": self.node_names[target],
            "edge_types": edge_types,
        }


def declaration_name(record: dict[str, Any], fallback: int) -> str:
    name = record.get("name")
    if isinstance(name, list):
        return ".".join(str(part) for part in name)
    if isinstance(name, str):
        return name
    return str(record.get("id") or record.get("index") or fallback)


def _module_key(record: dict[str, Any]) -> str:
    module_name = record.get("module_name")
    if isinstance(module_name, list):
        return ".".join(str(part) for part in module_name)
    if isinstance(module_name, str):
        return module_name
    module = record.get("module")
    return module if isinstance(module, str) else ""


def _ref_name(ref: Any) -> str:
    if isinstance(ref, list):
        return ".".join(str(part) for part in ref)
    return str(ref)


def _is_prop(record: dict[str, Any]) -> bool:
    if record.get("isProp") is True:
        return True
    return (record.get("kind") or "") == "theorem"


def _as_ref_list(value: Any) -> list[Any]:
    if value in (None, ""):
        return []
    if isinstance(value, (list, tuple, set)):
        return list(value)
    return [value]


def _structured_reference_items(
    record: dict[str, Any],
    fields: tuple[str, ...] | None = None,
    *,
    include_theorem_value_references: bool = False,
) -> list[tuple[str, Any]]:
    selected = set(fields or DEPENDENCY_FIELDS)
    refs: list[tuple[str, Any]] = []
    for field in _ALWAYS_STRUCTURED_FIELDS:
        if field in selected:
            refs.extend((field, ref) for ref in _as_ref_list(record.get(field)))
    if "typeReferences" in selected:
        refs.extend(("typeReferences", ref) for ref in _as_ref_list(record.get("typeReferences")))
    if "valueReferences" in selected and (
        not _is_prop(record) or include_theorem_value_references
    ):
        refs.extend(("valueReferences", ref) for ref in _as_ref_list(record.get("valueReferences")))
    return refs


def _structured_references(record: dict[str, Any]) -> list[Any]:
    return [ref for _, ref in _structured_reference_items(record)]


def _edge_weight_quantiles(values: list[float]) -> dict[str, float | None]:
    if not values:
        return {key: None for key in ("p0", "p25", "p50", "p75", "p90", "p95", "p99", "p100")}
    arr = np.asarray(values, dtype=np.float64)
    return {
        "p0": float(np.percentile(arr, 0)),
        "p25": float(np.percentile(arr, 25)),
        "p50": float(np.percentile(arr, 50)),
        "p75": float(np.percentile(arr, 75)),
        "p90": float(np.percentile(arr, 90)),
        "p95": float(np.percentile(arr, 95)),
        "p99": float(np.percentile(arr, 99)),
        "p100": float(np.percentile(arr, 100)),
    }


def _generated_metadata_value(record: dict[str, Any]) -> bool | None:
    for key in (
        "isGenerated",
        "is_generated",
        "auto_generated",
        "autoGenerated",
        "generated",
        "isAutoGenerated",
    ):
        if key not in record:
            continue
        value = record.get(key)
        if isinstance(value, bool):
            return value
        if isinstance(value, (int, float)):
            return bool(value)
        if isinstance(value, str):
            return value.strip().lower() in {"1", "true", "yes", "generated", "auto_generated"}
    return None


def _graph_artifact_type(dependency_source: str, structured_edges: int, text_edges: int) -> str:
    if dependency_source == "jixia_merged_jsonl" and structured_edges > 0:
        return "REAL_GRAPH_WITH_JIXIA_DEPENDENCIES"
    if text_edges > 0:
        return "REAL_GRAPH_TEXT_INFERRED_REFS"
    if structured_edges > 0:
        return "REAL_GRAPH_WITH_STRUCTURED_REFS"
    return "REAL_GRAPH_WITHOUT_DEPENDENCY_EDGES"


def _is_theorem_like(record: dict[str, Any]) -> bool:
    kind = str(record.get("kind") or "").lower()
    return bool(record.get("isProp") is True or "theorem" in kind or "lemma" in kind)


def _reverse_dependency_weight(
    *,
    base_weight: float,
    reference_frequency: int,
    target_is_theorem_like: bool,
    hub_penalty: str,
    theorem_like_weight: float,
    non_theorem_weight: float,
) -> float:
    """Weight an edge from a referenced declaration to one of its users.

    ``log2`` discounts reverse fan-out from dependency hubs while leaving a
    declaration referenced by only one source unchanged.  The declaration-kind
    multiplier acts on the reverse edge destination, so theorem/lemma users can
    be preferred without deleting definitions and instances from the graph.
    """

    if hub_penalty == "none":
        hub_factor = 1.0
    elif hub_penalty == "log2":
        hub_factor = 1.0 / math.log2(max(1, reference_frequency) + 1.0)
    else:
        raise GraphArtifactError(
            "reverse_dependency_hub_penalty must be one of: none, log2"
        )
    kind_factor = theorem_like_weight if target_is_theorem_like else non_theorem_weight
    return float(base_weight * hub_factor * kind_factor)


def _ordered_unique_targets(refs: list[Any], *, source: int, name_to_node: dict[str, int]) -> list[int]:
    seen: set[int] = set()
    targets: list[int] = []
    for ref in refs:
        target = name_to_node.get(_ref_name(ref))
        if target is None or target == source or target in seen:
            continue
        seen.add(target)
        targets.append(target)
    return targets


def _same_module_targets(members: list[int], source: int, limit: int) -> list[int]:
    if limit <= 0:
        return []
    return sorted((target for target in members if target != source), key=lambda target: (abs(target - source), target))[:limit]


def _build_text_reference_lookup(node_names: list[str]) -> dict[str, int]:
    lookup: dict[str, int] = {name: i for i, name in enumerate(node_names)}
    base_counts = Counter(name.rsplit(".", 1)[-1] for name in node_names)
    for i, name in enumerate(node_names):
        base = name.rsplit(".", 1)[-1]
        if len(base) >= 3 and base_counts[base] == 1:
            lookup.setdefault(base, i)
    return lookup


def _infer_text_reference_targets(
    record: dict[str, Any],
    *,
    source: int,
    lookup: dict[str, int],
    fields: tuple[str, ...],
    limit: int,
) -> set[int]:
    if limit <= 0:
        return set()
    targets: set[int] = set()
    for field in fields:
        text = record.get(field)
        if not text:
            continue
        for token in _LEAN_NAME_RE.findall(str(text)):
            target = lookup.get(token)
            if target is None or target == source:
                continue
            targets.add(target)
            if len(targets) >= limit:
                return targets
    return targets


def _metadata_path(path: Path) -> Path:
    if path.is_dir():
        return path / "metadata.pkl"
    return path


def _load_records(metadata_path: Path) -> list[dict[str, Any]]:
    raw_path = Path(metadata_path)
    path = _metadata_path(raw_path)
    if path.exists() and path.name.endswith(".pkl"):
        with path.open("rb") as f:
            payload = pickle.load(f)
        records = payload.get("data") if isinstance(payload, dict) else payload
        if not isinstance(records, list):
            raise GraphArtifactError(f"Expected metadata `data` list in {path}")
        return [r for r in records if isinstance(r, dict)]

    if raw_path.exists():
        try:
            records = list(iter_records_from_path(raw_path))
        except Exception as exc:
            raise GraphArtifactError(f"Could not load declaration records from {raw_path}: {exc}") from exc
        if records:
            return records

    raise GraphArtifactError(
        f"Missing corpus metadata or supported record files at {raw_path}. Build the cuVS corpus first, "
        "pass `--metadata-pkl`, or pass a supported .json/.jsonl/.jsonl.gz/.parquet record source."
    )


def _add_edge(
    adjacency: list[defaultdict[int, float]],
    edge_types: dict[tuple[int, int], set[str]],
    edge_counts: dict[str, int],
    source: int,
    target: int,
    weight: float,
    edge_type: str,
) -> bool:
    if source == target or weight <= 0:
        return False
    adjacency[source][target] += weight
    edge_types[(source, target)].add(edge_type)
    edge_counts[edge_type] += 1
    return True


def build_graph_artifact(
    metadata_path: str | Path,
    output_dir: str | Path,
    config: GraphConfig | None = None,
) -> GraphArtifact:
    cfg = config or GraphConfig()
    records = _load_records(Path(metadata_path))
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    node_names = [declaration_name(record, i) for i, record in enumerate(records)]
    name_to_node: dict[str, int] = {}
    for i, name in enumerate(node_names):
        name_to_node.setdefault(name, i)

    adjacency: list[defaultdict[int, float]] = [defaultdict(float) for _ in records]
    edge_types: dict[tuple[int, int], set[str]] = defaultdict(set)
    edge_counts: dict[str, int] = {
        "dep": 0,
        "proof_dep": 0,
        "rev_dep": 0,
        "same_module": 0,
        "semantic_knn": 0,
        "co_premise": 0,
    }

    weights = cfg.edge_weights
    selected_dependency_fields = tuple(field for field in cfg.dependency_fields if field in DEPENDENCY_FIELDS)
    dependency_field_weights = {str(k): float(v) for k, v in cfg.dependency_field_weights.items()}
    dependency_idf_fields = set(cfg.dependency_idf_fields)
    excluded_proof_source_names = set(cfg.excluded_proof_dependency_source_names)
    matched_excluded_proof_source_names = {
        name for name in excluded_proof_source_names if name in name_to_node
    }
    target_reference_frequency: Counter[int] = Counter()
    field_target_reference_frequency: dict[str, Counter[int]] = {
        field: Counter() for field in DEPENDENCY_FIELDS
    }
    for source, record in enumerate(records):
        source_targets: set[int] = set()
        field_source_targets: dict[str, set[int]] = defaultdict(set)
        source_name = node_names[source]
        for field, ref in _structured_reference_items(
            record,
            selected_dependency_fields,
            include_theorem_value_references=cfg.include_theorem_value_references,
        ):
            is_proof_dependency = field == "valueReferences" and _is_theorem_like(record)
            if is_proof_dependency and source_name in excluded_proof_source_names:
                continue
            target = name_to_node.get(_ref_name(ref))
            if target is None or target == source:
                continue
            source_targets.add(target)
            field_source_targets[field].add(target)
        target_reference_frequency.update(source_targets)
        for field, targets in field_source_targets.items():
            field_target_reference_frequency[field].update(targets)

    hub_targets: set[int] = set()
    dependency_hub_max_frequency = cfg.dependency_hub_max_frequency
    if dependency_hub_max_frequency is not None:
        hub_targets = {
            target
            for target, count in target_reference_frequency.items()
            if count > dependency_hub_max_frequency
        }
    generated_flags = [_generated_metadata_value(record) for record in records]
    generated_metadata_available = any(value is not None for value in generated_flags)
    generated_target_count = sum(1 for value in generated_flags if value is True)
    generated_penalty = float(cfg.generated_declaration_weight)

    def dependency_weight(field: str, target: int, *, is_proof_dependency: bool) -> float:
        value = weights.dep * dependency_field_weights.get(field, 1.0)
        if is_proof_dependency:
            value *= cfg.theorem_value_reference_weight
        if field in dependency_idf_fields:
            df = field_target_reference_frequency.get(field, Counter()).get(target, 0)
            value *= math.log((len(records) + 1.0) / (df + 1.0))
        if generated_flags[target] is True and generated_penalty >= 0:
            value *= generated_penalty
        return float(value)

    dependency_field_counts = {field: 0 for field in DEPENDENCY_FIELDS}
    dependency_field_edge_counts = {field: 0 for field in DEPENDENCY_FIELDS}
    records_with_reference_fields = 0
    records_with_text_references = 0
    structured_dependency_edges = 0
    text_reference_edges = 0
    dependency_hub_filtered_edges = 0
    generated_penalized_edges = 0
    reverse_theorem_like_edges = 0
    reverse_non_theorem_edges = 0
    reverse_edge_weight_values: list[float] = []
    proof_dependency_candidate_source_count = 0
    proof_dependency_candidate_item_count = 0
    proof_dependency_excluded_item_count = 0
    proof_dependency_weight_values: list[float] = []
    text_reference_lookup = _build_text_reference_lookup(node_names) if cfg.infer_text_references else {}
    for source, record in enumerate(records):
        source_name = node_names[source]
        if (
            cfg.include_theorem_value_references
            and _is_theorem_like(record)
            and _as_ref_list(record.get("valueReferences"))
        ):
            proof_dependency_candidate_source_count += 1
            item_count = len(_as_ref_list(record.get("valueReferences")))
            proof_dependency_candidate_item_count += item_count
            if source_name in excluded_proof_source_names:
                proof_dependency_excluded_item_count += item_count
        has_reference_field = False
        for field in selected_dependency_fields:
            if field in record:
                has_reference_field = True
                if _as_ref_list(record.get(field)):
                    dependency_field_counts[field] += 1
        if has_reference_field:
            records_with_reference_fields += 1

        seen_targets: set[int] = set()
        seen_field_targets: set[tuple[str, int]] = set()
        for field, ref in _structured_reference_items(
            record,
            selected_dependency_fields,
            include_theorem_value_references=cfg.include_theorem_value_references,
        ):
            is_proof_dependency = field == "valueReferences" and _is_theorem_like(record)
            if is_proof_dependency and source_name in excluded_proof_source_names:
                continue
            target = name_to_node.get(_ref_name(ref))
            if target is None:
                continue
            if target in hub_targets:
                dependency_hub_filtered_edges += 1
                continue
            if cfg.dependency_additive_fields:
                field_target = (field, target)
                if field_target in seen_field_targets:
                    continue
                seen_field_targets.add(field_target)
            elif target in seen_targets:
                continue
            weight = dependency_weight(
                field,
                target,
                is_proof_dependency=is_proof_dependency,
            )
            if generated_flags[target] is True and generated_penalty != 1.0:
                generated_penalized_edges += 1
            edge_type = "proof_dep" if is_proof_dependency else "dep"
            if _add_edge(
                adjacency,
                edge_types,
                edge_counts,
                source,
                target,
                weight,
                edge_type,
            ):
                structured_dependency_edges += 1
                dependency_field_edge_counts[field] += 1
                if is_proof_dependency:
                    proof_dependency_weight_values.append(weight)
            if target not in seen_targets:
                reverse_weight = _reverse_dependency_weight(
                    base_weight=weights.rev_dep,
                    reference_frequency=target_reference_frequency[target],
                    target_is_theorem_like=_is_theorem_like(record),
                    hub_penalty=cfg.reverse_dependency_hub_penalty,
                    theorem_like_weight=cfg.reverse_dependency_theorem_like_weight,
                    non_theorem_weight=cfg.reverse_dependency_non_theorem_weight,
                )
                if _add_edge(
                    adjacency,
                    edge_types,
                    edge_counts,
                    target,
                    source,
                    reverse_weight,
                    "rev_dep",
                ):
                    reverse_edge_weight_values.append(reverse_weight)
                    if _is_theorem_like(record):
                        reverse_theorem_like_edges += 1
                    else:
                        reverse_non_theorem_edges += 1
            seen_targets.add(target)

        if cfg.infer_text_references:
            text_targets = _infer_text_reference_targets(
                record,
                source=source,
                lookup=text_reference_lookup,
                fields=tuple(cfg.text_reference_fields),
                limit=cfg.max_text_refs_per_record,
            )
            new_text_targets = text_targets - seen_targets
            if new_text_targets:
                records_with_text_references += 1
            for target in sorted(new_text_targets):
                seen_targets.add(target)
                if _add_edge(adjacency, edge_types, edge_counts, source, target, weights.dep, "dep"):
                    text_reference_edges += 1
                reverse_weight = _reverse_dependency_weight(
                    base_weight=weights.rev_dep,
                    reference_frequency=target_reference_frequency[target],
                    target_is_theorem_like=_is_theorem_like(record),
                    hub_penalty=cfg.reverse_dependency_hub_penalty,
                    theorem_like_weight=cfg.reverse_dependency_theorem_like_weight,
                    non_theorem_weight=cfg.reverse_dependency_non_theorem_weight,
                )
                if _add_edge(
                    adjacency,
                    edge_types,
                    edge_counts,
                    target,
                    source,
                    reverse_weight,
                    "rev_dep",
                ):
                    reverse_edge_weight_values.append(reverse_weight)
                    if _is_theorem_like(record):
                        reverse_theorem_like_edges += 1
                    else:
                        reverse_non_theorem_edges += 1

    same_module_edge_generation = "disabled_by_zero_weight"
    same_module_large_modules_capped = 0
    same_module_module_count = 0
    if weights.same_module > 0:
        by_module: dict[str, list[int]] = defaultdict(list)
        for i, record in enumerate(records):
            module = _module_key(record)
            if module:
                by_module[module].append(i)
        same_module_module_count = sum(1 for members in by_module.values() if len(members) > 1)
        same_module_edge_generation = "capped"
        for members in by_module.values():
            if len(members) <= 1:
                continue
            members = sorted(members)
            if len(members) > cfg.same_module_max_module_size:
                same_module_large_modules_capped += 1
            for source in members:
                for target in _same_module_targets(members, source, cfg.same_module_max_neighbors_per_node):
                    _add_edge(adjacency, edge_types, edge_counts, source, target, weights.same_module, "same_module")

    co_premise_edge_generation = "disabled"
    co_premise_candidate_source_count = 0
    co_premise_source_count = 0
    co_premise_ref_frequency: Counter[int] = Counter()
    co_premise_hub_reference_count = 0
    co_premise_weighted_additions = 0
    if cfg.enable_co_premise_edges and weights.co_premise > 0:
        co_premise_edge_generation = "enabled"
        source_refs: dict[int, list[int]] = {}
        for source, record in enumerate(records):
            if cfg.co_premise_theorem_like_only and not _is_theorem_like(record):
                continue
            refs = _ordered_unique_targets(
                _as_ref_list(record.get("valueReferences")),
                source=source,
                name_to_node=name_to_node,
            )
            if len(refs) < 2:
                continue
            co_premise_candidate_source_count += 1
            source_refs[source] = refs
            co_premise_ref_frequency.update(refs)

        hub_targets = {
            target for target, count in co_premise_ref_frequency.items()
            if count > cfg.co_premise_max_ref_frequency
        }
        co_premise_hub_reference_count = len(hub_targets)
        for source, refs in sorted(source_refs.items()):
            filtered = [target for target in refs if target not in hub_targets]
            filtered = sorted(filtered, key=lambda target: node_names[target])[: cfg.co_premise_max_refs_per_source]
            if len(filtered) < 2:
                continue
            co_premise_source_count += 1
            pair_weight = weights.co_premise / float(np.log(2 + len(filtered)))
            for i, left in enumerate(filtered):
                for right in filtered[i + 1:]:
                    if _add_edge(adjacency, edge_types, edge_counts, left, right, pair_weight, "co_premise"):
                        co_premise_weighted_additions += 1
                    if _add_edge(adjacency, edge_types, edge_counts, right, left, pair_weight, "co_premise"):
                        co_premise_weighted_additions += 1

    adjacency_dicts: list[dict[int, float]] = [dict(neighbors) for neighbors in adjacency]
    edge_weight_values = [float(value) for neighbors in adjacency_dicts for value in neighbors.values()]
    out_degree = [len(neighbors) for neighbors in adjacency_dicts]
    in_degree = [0 for _ in records]
    for neighbors in adjacency_dicts:
        for target in neighbors:
            in_degree[target] += 1

    edge_stats = {
        "num_nodes": len(records),
        "num_edges": int(sum(len(neighbors) for neighbors in adjacency_dicts)),
        "edge_counts": edge_counts,
        "edge_weights": weights.as_dict(),
        "dependency_source": cfg.dependency_source,
        "graph_artifact_type": _graph_artifact_type(
            cfg.dependency_source, structured_dependency_edges, text_reference_edges
        ),
        "dependency_fields": list(selected_dependency_fields),
        "dependency_field_weights": dependency_field_weights,
        "dependency_idf_fields": sorted(dependency_idf_fields),
        "dependency_additive_fields": cfg.dependency_additive_fields,
        "proof_dependency_policy": {
            "enabled": cfg.include_theorem_value_references,
            "source_kinds": "theorem/lemma/Prop-like declarations",
            "reference_field": "valueReferences",
            "edge_type": "proof_dep",
            "weight_multiplier": cfg.theorem_value_reference_weight,
            "candidate_source_count": proof_dependency_candidate_source_count,
            "candidate_reference_item_count": proof_dependency_candidate_item_count,
            "added_edge_count": edge_counts["proof_dep"],
            "edge_weight_quantiles": _edge_weight_quantiles(
                proof_dependency_weight_values
            ),
            "excluded_source_name_count_requested": len(excluded_proof_source_names),
            "excluded_source_name_count_matched": len(
                matched_excluded_proof_source_names
            ),
            "excluded_source_names_matched": sorted(
                matched_excluded_proof_source_names
            ),
            "excluded_source_names_absent": sorted(
                excluded_proof_source_names - matched_excluded_proof_source_names
            ),
            "excluded_reference_item_count": proof_dependency_excluded_item_count,
        },
        "records_with_reference_fields": records_with_reference_fields,
        "missing_reference_fields": len(records) - records_with_reference_fields,
        "dependency_field_counts": dependency_field_counts,
        "dependency_field_edge_counts": dependency_field_edge_counts,
        "type_reference_edge_count": dependency_field_edge_counts["typeReferences"],
        "value_reference_edge_count": dependency_field_edge_counts["valueReferences"],
        "hub_filter_stats": {
            "enabled": dependency_hub_max_frequency is not None,
            "max_reference_frequency": dependency_hub_max_frequency,
            "hub_target_count": len(hub_targets),
            "filtered_edge_count": dependency_hub_filtered_edges,
            "top_hub_targets": [
                {"name": node_names[target], "frequency": int(target_reference_frequency[target])}
                for target in sorted(
                    hub_targets,
                    key=lambda item: (-target_reference_frequency[item], node_names[item]),
                )[:20]
            ],
        },
        "generated_declaration_filter_stats": {
            "metadata_available": generated_metadata_available,
            "generated_target_count": generated_target_count,
            "penalty": generated_penalty,
            "penalized_edge_count": generated_penalized_edges,
        },
        "weight_quantiles": _edge_weight_quantiles(edge_weight_values),
        "edge_weight_quantiles": _edge_weight_quantiles(edge_weight_values),
        "infer_text_references": cfg.infer_text_references,
        "text_reference_fields": list(cfg.text_reference_fields),
        "max_text_refs_per_record": cfg.max_text_refs_per_record,
        "records_with_text_references": records_with_text_references,
        "text_reference_edges": text_reference_edges,
        "structured_dependency_edge_count": structured_dependency_edges,
        "text_inferred_edge_count": text_reference_edges,
        "same_module_edge_count": edge_counts["same_module"],
        "same_module_max_neighbors_per_node": cfg.same_module_max_neighbors_per_node,
        "same_module_max_module_size": cfg.same_module_max_module_size,
        "same_module_module_count": same_module_module_count,
        "same_module_large_modules_capped": same_module_large_modules_capped,
        "reverse_edge_count": edge_counts["rev_dep"],
        "reverse_dependency_policy": {
            "hub_penalty": cfg.reverse_dependency_hub_penalty,
            "hub_penalty_formula": (
                "1/log2(reference_frequency+1)"
                if cfg.reverse_dependency_hub_penalty == "log2"
                else "1"
            ),
            "theorem_like_weight": cfg.reverse_dependency_theorem_like_weight,
            "non_theorem_weight": cfg.reverse_dependency_non_theorem_weight,
            "theorem_like_edge_count": reverse_theorem_like_edges,
            "non_theorem_edge_count": reverse_non_theorem_edges,
            "reverse_edge_weight_quantiles": _edge_weight_quantiles(
                reverse_edge_weight_values
            ),
        },
        "same_module_edge_generation": same_module_edge_generation,
        "co_premise_edge_generation": co_premise_edge_generation,
        "co_premise_edge_count": edge_counts["co_premise"],
        "co_premise_source_count": co_premise_source_count,
        "co_premise_candidate_source_count": co_premise_candidate_source_count,
        "co_premise_hub_reference_count": co_premise_hub_reference_count,
        "co_premise_max_refs_per_source": cfg.co_premise_max_refs_per_source,
        "co_premise_max_ref_frequency": cfg.co_premise_max_ref_frequency,
        "co_premise_theorem_like_only": cfg.co_premise_theorem_like_only,
        "co_premise_weighted_additions": co_premise_weighted_additions,
    }

    transition, dangling = transition_matrix_from_adjacency(adjacency_dicts)

    artifact = GraphArtifact(
        adjacency=adjacency_dicts,
        node_names=node_names,
        node_records=records,
        name_to_node=name_to_node,
        edge_stats=edge_stats,
        edge_types={k: sorted(v) for k, v in edge_types.items()},
        in_degree=in_degree,
        out_degree=out_degree,
        transition=transition,
        dangling=dangling,
    )
    _write_artifact(artifact, output)
    return artifact


def _write_artifact(artifact: GraphArtifact, output_dir: Path) -> None:
    src: list[int] = []
    dst: list[int] = []
    weight: list[float] = []
    edge_rows: list[dict[str, Any]] = []
    for source, neighbors in enumerate(artifact.adjacency):
        for target, value in sorted(neighbors.items()):
            src.append(source)
            dst.append(target)
            weight.append(float(value))
            edge_rows.append(
                {
                    "source": source,
                    "target": target,
                    "weight": float(value),
                    "edge_types": artifact.edge_types.get((source, target), []),
                }
            )
    np.savez(
        output_dir / ADJACENCY_FILE,
        src=np.asarray(src, dtype=np.int64),
        dst=np.asarray(dst, dtype=np.int64),
        weight=np.asarray(weight, dtype=np.float64),
        n=np.asarray([len(artifact.node_names)], dtype=np.int64),
    )
    nodes = [
        {"node_id": i, "name": name, "record": artifact.node_records[i]}
        for i, name in enumerate(artifact.node_names)
    ]
    (output_dir / NODES_FILE).write_text(json.dumps(nodes, ensure_ascii=False, indent=2), encoding="utf-8")
    (output_dir / EDGES_FILE).write_text(json.dumps(edge_rows, ensure_ascii=False, indent=2), encoding="utf-8")
    (output_dir / STATS_FILE).write_text(json.dumps(artifact.edge_stats, indent=2), encoding="utf-8")


def load_graph_artifact(artifact_dir: str | Path) -> GraphArtifact:
    root = Path(artifact_dir)
    missing = [
        name
        for name in (ADJACENCY_FILE, NODES_FILE, EDGES_FILE, STATS_FILE)
        if not (root / name).exists()
    ]
    if missing:
        raise GraphArtifactError(
            f"Missing graph artifact file(s) in {root}: {', '.join(missing)}. "
            "Run `python -m leansearchv2.graph.build --metadata-pkl <cuvs_db>/metadata.pkl "
            "--output-dir <graph_dir>` to build the graph artifact."
        )

    raw = np.load(root / ADJACENCY_FILE)
    n = int(raw["n"][0])
    adjacency: list[dict[int, float]] = [dict() for _ in range(n)]
    for source, target, value in zip(raw["src"], raw["dst"], raw["weight"]):
        adjacency[int(source)][int(target)] = float(value)
    transition, dangling = transition_matrix_from_edges(n, raw["src"], raw["dst"], raw["weight"])

    nodes = json.loads((root / NODES_FILE).read_text(encoding="utf-8"))
    node_names = [str(node["name"]) for node in nodes]
    node_records = [dict(node.get("record") or {}) for node in nodes]
    name_to_node = {name: i for i, name in enumerate(node_names)}

    edge_rows = json.loads((root / EDGES_FILE).read_text(encoding="utf-8"))
    edge_types = {
        (int(row["source"]), int(row["target"])): list(row.get("edge_types") or [])
        for row in edge_rows
    }
    edge_stats = json.loads((root / STATS_FILE).read_text(encoding="utf-8"))

    out_degree = [len(neighbors) for neighbors in adjacency]
    in_degree = [0 for _ in range(n)]
    for neighbors in adjacency:
        for target in neighbors:
            in_degree[target] += 1

    return GraphArtifact(
        adjacency=adjacency,
        node_names=node_names,
        node_records=node_records,
        name_to_node=name_to_node,
        edge_stats=edge_stats,
        edge_types=edge_types,
        in_degree=in_degree,
        out_degree=out_degree,
        transition=transition,
        dangling=dangling,
    )
